#! /bin/bash

echo Running Pandoc...
pandoc \
	--pdf-engine=xelatex \
	--template=./cover_letter/CLtemplate.tex \
	-s ./cover_letter/coverletter.md \
	-f markdown \
	-t latex \
	-o ./cover_letter/coverletter.pdf
echo Done
